### ISSUE TITLE
Cannot read property error

### ISSUE THREAD

**Issue by cmbirk** [2fdevs/bower-videogular-analytics#5]
```
Cannot read property 'category' of undefined
    at r.scope.addWatchers (http://local.artbot.co/bower_components/videogular-angulartics/vg-analytics.js:125:42)
    at link (http://local.artbot.co/bower_components/videogular-angulartics/vg-analytics.js:216:27)
    at http://local.artbot.co/bower_components/angular/angular.min.js:73:236
    at ea (http://local.artbot.co/bower_components/angular/angular.min.js:73:293)
    at D (http://local.artbot.co/bower_components/angular/angular.min.js:62:190)
    at g (http://local.artbot.co/bower_components/angular/angular.min.js:55:105)
    at D (http://local.artbot.co/bower_components/angular/angular.min.js:62:134)
    at g (http://local.artbot.co/bower_components/angular/angular.min.js:55:105)
    at g (http://local.artbot.co/bower_components/angular/angular.min.js:55:122)
    at g (http://local.artbot.co/bower_components/angular/angular.min.js:55:122) <vg-analytics vg-track-info="events" class="ng-isolate-scope">
```

and the line in question looks like: 

```
 scope.addWatchers = function () {
Error here--->                    if (scope.vgTrackInfo.category || scope.vgTrackInfo.label) {
                        info = {};

                        scope.updateTrackInfo(scope.vgTrackInfo);
                    }
```

**Comment by cmbirk** [comment]
I think this is happening because my video is being loaded via an API call and so the angulartics plugin is trying to start before the video and the configuration is added

**Comment by cmbirk** [comment]
I'm using `ui-router`'s `resolve` method to load the video before initializing my controller, but still running into this issue

**Comment by cmbirk** [comment]
This was an issue with the config pointing to the wrong plugin object.  I apologize for the unnecessary ticket.

**Comment by Elecash** [comment]
No apologies please! And thank you for commenting how you fixed it :)

**Comment by mddanishyusuf** [comment]
@cmbirk can you explain how you resolve this problem because i also facing this problem.
